### ISSUE TITLE
cannot select mulitple weeks on mobile touch devices

### ISSUE THREAD

**Issue by krisred** [FOLLGAD/week-picker#1]
When touching or dragging to select multiple weeks, does not work. Also, on touch based devices it would be better to detect touch and set the input to read only so the keyboard does not popup thanks!

Great plugin! Thank you!

**Comment by FOLLGAD** [comment]
Glad that you like it! I have fixed those issues you brought up.
If you have other questions you're welcome to ask!

**Comment by krisred** [comment]
Thank you fixing it., Now it does not work on desktop with mouse.
Another suggestion would be able to have method to get selected week or range, onSelected event as well that passes selected week or week range as parameter

**Comment by krisred** [comment]
forgot to mention, I tested it used the demo link

**Comment by FOLLGAD** [comment]
Sorry, I had forgotten to build. It should work as expected now.
